<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Chamado;

/**
 * ChamadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChamadoRepository extends \Doctrine\ORM\EntityRepository
{
    public function novo($em, array $dados)
    {
        $chamado = new Chamado();
        $chamado->setTitulo($dados['titulo']);
        $chamado->setObservacao($dados['observacao']);
        $chamado->setCliente($dados['cliente']);
        $chamado->setPedido($dados['pedido']);
        
        $em->persist($chamado);
        $em->flush();

        return $chamado;
    }
}
