<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cliente;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrCreate($em, array $dados)
    {
        $cliente = $this->findOneByEmail($dados['email']);
        if (is_null($cliente) || empty($cliente)) {
            $cliente = new Cliente();
            $cliente->setNome($dados['nome']);
            $cliente->setEmail($dados['email']);
    
            $em->persist($cliente);
            $em->flush();
        }

        return $cliente;
    }
}
