<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Pedido;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends \Doctrine\ORM\EntityRepository
{
    public function novo($em, array $dados)
    {
        $pedido = new Pedido();
        $pedido->setNumero($dados['numero']);
        
        $em->persist($pedido);
        $em->flush();
        
        return $pedido;
    }
}
