AppBundle\Entity\Chamado:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ChamadoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: '150'
        observacao:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        cliente:
            targetEntity: Cliente
            inversedBy: chamados
            joinColumn:
                name: cliente_id
                referencedColumnName: id
        pedido:
            targetEntity: Pedido
            inversedBy: chamados
            joinColumn:
                name: pedido_id
                referencedColumnName: id
